### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by Ayan-Banerjee-918** [Supertigerr/better-in-game-chat#1]
How to setup server? It keeps saying not connected yet!

**Comment by SupertigerDev** [comment]
Hello, did you use the `/connect <ip>` command?

Did you start the server?

**Comment by Ayan-Banerjee-918** [comment]
Hey,thanks for the quick response...Can you guide me a bit?

I have installed the software,and i start the exe..Whats next? How do i start the server?

**Comment by SupertigerDev** [comment]
Hello, no problem 😊 Unfortunately, there's no exe for the server. You have to install node.js and run the code yourself. I could create an exe file for the server if you could give me a couple of minutes.

**Comment by Ayan-Banerjee-918** [comment]
Sure,that would be great!! 
I have nodejs as well....So you can tell me how to setup via node as well

**Comment by SupertigerDev** [comment]
Ah, great! go into the server folder, run these commands
```
npm install
npm start
```
and it should start the server

**Comment by Ayan-Banerjee-918** [comment]
Yes ,that worked superbly!!

Now suppose my friend and I want to chat via this...So what should my friend use to connect to the server that i host?

Edit: I asked my friend to do /connect <my ip> and it got stuck at connecting...

**Comment by SupertigerDev** [comment]
Unless you live in the same house, if you're hosting the server on your computer, you will need to open the port 8080 in your router settings so your friend can connect, using your public IP address & port. 

To get your IP https://whatismyipaddress.com/

**Comment by Ayan-Banerjee-918** [comment]
okay, so is it /connect ip:port ?
or only /connect ip?

**Comment by SupertigerDev** [comment]
Like this it seems: `/connect http://YourIP:8080`

**Comment by Ayan-Banerjee-918** [comment]
Awesome!! Thanks so much for the quick responses!!

Everything works!! Thanks a lot again!!

**Comment by SupertigerDev** [comment]
<33 no problem, Glad to see someone try out this project. I've also attached the exe for the server at https://github.com/SupertigerDev/better-in-game-chat/releases/tag/1.3.1

**Comment by Ayan-Banerjee-918** [comment]
Awesome!! 😊

**Comment by SupertigerDev** [comment]
I'm going to close this issue now, If you have any other problems, feel free to open another issue, or contact me via discord 😄

**Comment by itsKD007** [comment]
Hey thanks a lot from my side as well...I am the one who has connected with Ayan...Great lightweight interface you have built here...

**Comment by SupertigerDev** [comment]
Thanks! ❤️ The design is hugely inspired by the Overwatch 1 chat system
